.catalog:
  name: "LNMP SERVER"
  description: escription of the versioned template of the Catalog Entry
  version: "v1.0"
  questions:
    - variable: "SERVER_NAME2"
      label: ServerName
      description:  站点的域名
      type: "string"     
    - variable: "WEB_SITE2"
      label: WebSite
      description: nginx站点中项目的根目录
      type: "string"
